"""
Core Enums xác định các phân loại Nhận thức, Yêu cầu, Quyền sở hữu, Bộ nhớ và Truy xuất (Nhắc 1, 2, 3, 4).
"""

from enum import Enum


class ClaimType(str, Enum):
    """Các loại luận điểm (claim) chuẩn (RC-05)."""
    SOURCE_FACT = "SOURCE_FACT"
    SOURCE_CLAIM = "SOURCE_CLAIM"
    SYNTHESIS = "SYNTHESIS"
    OUR_INFERENCE = "OUR_INFERENCE"
    OUR_DESIGN = "OUR_DESIGN"
    EXPERIMENT_RESULT = "EXPERIMENT_RESULT"
    HYPOTHESIS = "HYPOTHESIS"


class IntellectualOwnership(str, Enum):
    """Ranh giới sở hữu trí tuệ 4 cấp độ Canonical (RC-06, Phần 4)."""
    SOURCE = "SOURCE"
    ADAPTED = "ADAPTED"
    OURS = "OURS"
    BASELINE = "BASELINE"


class EpistemicStatus(str, Enum):
    """Ma trận vòng đời trạng thái nhận thức (RC-07)."""
    UNVERIFIED = "UNVERIFIED"
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    CONTESTED = "CONTESTED"
    FALSIFIED = "FALSIFIED"
    SUPERSEDED = "SUPERSEDED"


class SourceVerificationState(str, Enum):
    """Các trạng thái xác minh thư mục và nội dung (Phần 7)."""
    DISCOVERED = "DISCOVERED"
    METADATA_VERIFIED = "METADATA_VERIFIED"
    CONTENT_VERIFIED = "CONTENT_VERIFIED"
    INGESTED = "INGESTED"
    SUPERSEDED = "SUPERSEDED"
    RETRACTED = "RETRACTED"
    UNAVAILABLE = "UNAVAILABLE"


class SourceRole(str, Enum):
    """Vai trò chức năng của nguồn bên ngoài trong biểu đồ nghiên cứu (Phần 18)."""
    DEFINITION = "DEFINITION"
    BACKGROUND = "BACKGROUND"
    METHOD = "METHOD"
    BASELINE = "BASELINE"
    DATASET = "DATASET"
    VALIDITY = "VALIDITY"
    ROBUSTNESS = "ROBUSTNESS"
    PRIVACY = "PRIVACY"
    REPRODUCIBILITY = "REPRODUCIBILITY"
    METRIC = "METRIC"
    CONTRADICTORY_EVIDENCE = "CONTRADICTORY_EVIDENCE"
    IMPLEMENTATION_REFERENCE = "IMPLEMENTATION_REFERENCE"
    EMERGING_WORK = "EMERGING_WORK"


class SourceQualityTier(str, Enum):
    """Phân loại chất lượng thư mục và xuất xứ (Phần 19)."""
    PRIMARY_STANDARD = "PRIMARY_STANDARD"
    PEER_REVIEWED_TOP_VENUE = "PEER_REVIEWED_TOP_VENUE"
    PEER_REVIEWED = "PEER_REVIEWED"
    OFFICIAL_DATASET = "OFFICIAL_DATASET"
    INSTITUTIONAL_REPORT = "INSTITUTIONAL_REPORT"
    PREPRINT = "PREPRINT"
    SOFTWARE_ARTIFACT = "SOFTWARE_ARTIFACT"
    SECONDARY_SURVEY = "SECONDARY_SURVEY"
    DISCOVERY_ONLY = "DISCOVERY_ONLY"


class SupportType(str, Enum):
    """Mối quan hệ loại hỗ trợ Tường lửa trích dẫn (Phần 10)."""
    DIRECT_SUPPORT = "DIRECT_SUPPORT"
    PARTIAL_SUPPORT = "PARTIAL_SUPPORT"
    BACKGROUND = "BACKGROUND"
    MOTIVATION = "MOTIVATION"
    CONTRADICTION = "CONTRADICTION"
    METHOD_SOURCE = "METHOD_SOURCE"
    DATASET_SOURCE = "DATASET_SOURCE"
    BASELINE_SOURCE = "BASELINE_SOURCE"


class EvidenceStrength(str, Enum):
    """Độ mạnh phân loại của ràng buộc bằng chứng (Phần 11)."""
    STRONG = "STRONG"
    MODERATE = "MODERATE"
    WEAK = "WEAK"


class NoveltyStatus(str, Enum):
    """Trạng thái vòng đời đánh giá mới lạ đối với đóng góp của ứng viên (Phần 17)."""
    CANDIDATE = "CANDIDATE"
    PRIOR_ART_SEARCHED = "PRIOR_ART_SEARCHED"
    POTENTIALLY_NOVEL = "POTENTIALLY_NOVEL"
    NOT_NOVEL = "NOT_NOVEL"
    PARTIALLY_NOVEL = "PARTIALLY_NOVEL"
    NOVELTY_UNRESOLVED = "NOVELTY_UNRESOLVED"


class CitationFirewallStatus(str, Enum):
    """Trạng thái sẵn sàng trích dẫn trong Tường lửa trích dẫn (Phần 10)."""
    READY = "READY"
    BLOCKED = "BLOCKED"
    UNRESOLVED = "UNRESOLVED"


class EquationType(str, Enum):
    """Phân loại xuất xứ phương trình (RC-08)."""
    SOURCE_EQUATION = "SOURCE_EQUATION"
    DERIVED_EQUATION = "DERIVED_EQUATION"
    PROPOSED_EQUATION = "PROPOSED_EQUATION"


class ArgumentRelationType(str, Enum):
    """Quan hệ cạnh đồ thị đối số (Phần 11)."""
    SUPPORTS = "SUPPORTS"
    CONTRADICTS = "CONTRADICTS"
    QUALIFIES = "QUALIFIES"
    DEPENDS_ON = "DEPENDS_ON"
    ASSUMES = "ASSUMES"
    DERIVED_FROM = "DERIVED_FROM"
    GENERALIZES = "GENERALIZES"
    SPECIALIZES = "SPECIALIZES"
    FALSIFIES = "FALSIFIES"
    REPLICATES = "REPLICATES"
    FAILS_TO_REPLICATE = "FAILS_TO_REPLICATE"
    MOTIVATES = "MOTIVATES"
    COMPARES_WITH = "COMPARES_WITH"


class VerificationStatus(str, Enum):
    """Các quốc gia xác minh."""
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    INCONCLUSIVE = "INCONCLUSIVE"


class MemoryTier(str, Enum):
    """Kiến trúc bộ nhớ nghiên cứu 6 tầng Canonical (Lời Prompt 4 Phần 5)."""
    M0_WORKING = "M0_WORKING"
    M1_SOURCE = "M1_SOURCE"
    M2_SEMANTIC = "M2_SEMANTIC"
    M3_EPISODIC = "M3_EPISODIC"
    M4_ARGUMENT = "M4_ARGUMENT"
    M5_PROCEDURAL = "M5_PROCEDURAL"


class MemoryRecordType(str, Enum):
    """Đã đánh máy Danh mục bản ghi bộ nhớ nghiên cứu (Prompt 4 Phần 6)."""
    FACT_REFERENCE = "FACT_REFERENCE"
    CLAIM_REFERENCE = "CLAIM_REFERENCE"
    EVIDENCE_REFERENCE = "EVIDENCE_REFERENCE"
    DECISION = "DECISION"
    OBSERVATION = "OBSERVATION"
    EXPERIMENT_EPISODE = "EXPERIMENT_EPISODE"
    FAILURE = "FAILURE"
    LESSON = "LESSON"
    OPEN_QUESTION = "OPEN_QUESTION"
    TODO = "TODO"
    ASSUMPTION = "ASSUMPTION"
    CONTRADICTION = "CONTRADICTION"
    HYPOTHESIS_UPDATE = "HYPOTHESIS_UPDATE"
    METHODOLOGY_CONSTRAINT = "METHODOLOGY_CONSTRAINT"
    USER_DECISION = "USER_DECISION"
    PROCEDURE = "PROCEDURE"
    SYSTEM_CHANGE = "SYSTEM_CHANGE"


class MemoryPromotionState(str, Enum):
    """Các trạng thái vòng đời hợp nhất bộ nhớ (Lời Prompt 4 Phần 13)."""
    CAPTURED = "CAPTURED"
    CLASSIFIED = "CLASSIFIED"
    VALIDATED = "VALIDATED"
    CONSOLIDATED = "CONSOLIDATED"
    REJECTED = "REJECTED"
    TEMPORARY = "TEMPORARY"


class DecisionStatus(str, Enum):
    """Trạng thái quyết định về kiến ​​trúc và nghiên cứu (Prompt 4 Phần 31)."""
    ACTIVE = "ACTIVE"
    ACCEPTED = "ACCEPTED"
    SUPERSEDED = "SUPERSEDED"
    REVERSED = "REVERSED"
    EXPERIMENTAL = "EXPERIMENTAL"
    PENDING = "PENDING"
    REJECTED = "REJECTED"


class OpenQuestionStatus(str, Enum):
    """Các trạng thái vòng đời của câu hỏi nghiên cứu mở (Lời Prompt 4 Phần 32)."""
    OPEN = "OPEN"
    INVESTIGATING = "INVESTIGATING"
    RESOLVED = "RESOLVED"
    BLOCKED = "BLOCKED"
    ABANDONED = "ABANDONED"


class EpisodeStatus(str, Enum):
    """Trạng thái vòng đời sự kiện theo từng giai đoạn (Lời Prompt 4 Phần 5)."""
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ABORTED = "ABORTED"
    IN_PROGRESS = "IN_PROGRESS"


class SkillStatus(str, Enum):
    """Trạng thái Vòng đời Kỹ năng Thủ tục (Prompt 4 Phần 35)."""
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    DEPRECATED = "DEPRECATED"
    SUPERSEDED = "SUPERSEDED"


class QueryIntentType(str, Enum):
    """Phân loại mục đích truy xuất kết hợp (Prompt 4 Phần 21)."""
    SOURCE_LOOKUP = "SOURCE_LOOKUP"
    CLAIM_LOOKUP = "CLAIM_LOOKUP"
    EVIDENCE_LOOKUP = "EVIDENCE_LOOKUP"
    ROADMAP_LOOKUP = "ROADMAP_LOOKUP"
    ARGUMENT_LOOKUP = "ARGUMENT_LOOKUP"
    CONTRADICTION_LOOKUP = "CONTRADICTION_LOOKUP"
    DECISION_LOOKUP = "DECISION_LOOKUP"
    EXPERIMENT_LOOKUP = "EXPERIMENT_LOOKUP"
    HISTORY_LOOKUP = "HISTORY_LOOKUP"
    CURRENT_STATE = "CURRENT_STATE"
    OPEN_QUESTION_LOOKUP = "OPEN_QUESTION_LOOKUP"
    CONTRIBUTION_LOOKUP = "CONTRIBUTION_LOOKUP"
    PROCEDURE_LOOKUP = "PROCEDURE_LOOKUP"
    SEMANTIC_DISCOVERY = "SEMANTIC_DISCOVERY"


class PrivacyClassification(str, Enum):
    """Nghiên cứu ranh giới quyền riêng tư và truy cập bộ nhớ (Lời Prompt 4 Phần 48)."""
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    SENSITIVE = "SENSITIVE"
    RESTRICTED = "RESTRICTED"


class ExperimentStatus(str, Enum):
    """Thử nghiệm và chạy vòng đời (RC-10, RC-14)."""
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ABORTED = "ABORTED"


class ArtifactCategory(str, Enum):
    """Danh mục artifact kinh điển."""
    EQUATION = "EQUATION"
    TABLE = "TABLE"
    FIGURE = "FIGURE"
    DATASET_SPLIT = "DATASET_SPLIT"
    MODEL_WEIGHT = "MODEL_WEIGHT"
    LOG_FEATURE_VECTOR = "LOG_FEATURE_VECTOR"
    SPECIFICATION = "SPECIFICATION"
    REPORT = "REPORT"


# ----------------------------------------------------------------------
# PROMPT 5 ENUMS: Lập luận và lập luận khoa học (Phần 5..48)
# ----------------------------------------------------------------------

class ReasoningMode(str, Enum):
    """Các phương thức suy luận khoa học (Gợi ý 5 Phần 5)."""
    DEFINITIONAL = "DEFINITIONAL"
    COMPARATIVE = "COMPARATIVE"
    DEDUCTIVE = "DEDUCTIVE"
    INDUCTIVE = "INDUCTIVE"
    ABDUCTIVE = "ABDUCTIVE"
    MECHANISTIC = "MECHANISTIC"
    COUNTERFACTUAL = "COUNTERFACTUAL"
    CONTRADICTION_ANALYSIS = "CONTRADICTION_ANALYSIS"
    FALSIFICATION = "FALSIFICATION"
    CAUSALITY_CHECK = "CAUSALITY_CHECK"
    VALIDITY_ANALYSIS = "VALIDITY_ANALYSIS"
    METHODOLOGY_CRITIQUE = "METHODOLOGY_CRITIQUE"
    EVIDENCE_SYNTHESIS = "EVIDENCE_SYNTHESIS"
    HYPOTHESIS_EVALUATION = "HYPOTHESIS_EVALUATION"
    NOVELTY_DIFFERENTIATION = "NOVELTY_DIFFERENTIATION"
    EXPERIMENT_INTERPRETATION = "EXPERIMENT_INTERPRETATION"


class EvidenceAlignmentStatus(str, Enum):
    """Phân loại căn chỉnh bằng chứng (Nhắc 5 Phần 10)."""
    DIRECT_SUPPORT = "DIRECT_SUPPORT"
    PARTIAL_SUPPORT = "PARTIAL_SUPPORT"
    BACKGROUND = "BACKGROUND"
    CONTRADICTION = "CONTRADICTION"
    QUALIFICATION = "QUALIFICATION"
    IRRELEVANT = "IRRELEVANT"
    INSUFFICIENT = "INSUFFICIENT"


class ContradictionType(str, Enum):
    """Loại hình mâu thuẫn chi tiết (Nhắc 5 Phần 15)."""
    TRUE_CONTRADICTION = "TRUE_CONTRADICTION"
    APPARENT_CONTRADICTION = "APPARENT_CONTRADICTION"
    SCOPE_DIFFERENCE = "SCOPE_DIFFERENCE"
    METHODOLOGY_DIFFERENCE = "METHODOLOGY_DIFFERENCE"
    METRIC_DIFFERENCE = "METRIC_DIFFERENCE"
    DATASET_DIFFERENCE = "DATASET_DIFFERENCE"
    UNRESOLVED = "UNRESOLVED"


class NegativeResultType(str, Enum):
    """Hạng mục Giải thích Kết quả Âm tính (Nhắc 5 Phần 46)."""
    TECHNICAL_FAILURE = "TECHNICAL_FAILURE"
    NULL_RESULT = "NULL_RESULT"
    NEGATIVE_RESULT = "NEGATIVE_RESULT"
    HYPOTHESIS_FALSIFICATION = "HYPOTHESIS_FALSIFICATION"
    INCONCLUSIVE_RESULT = "INCONCLUSIVE_RESULT"


class ArgumentReadinessState(str, Enum):
    """Vòng đời sẵn sàng của ArgumentBundle (Lời nhắc 5 Phần 64)."""
    DRAFT = "DRAFT"
    EVIDENCE_INCOMPLETE = "EVIDENCE_INCOMPLETE"
    CONTESTED = "CONTESTED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    READY = "READY"
    BLOCKED = "BLOCKED"


class ReasoningIssueType(str, Enum):
    """Phân loại các vấn đề về lý luận và kiểm tra phương pháp luận (Nhắc 5 Phần 63)."""
    UNSUPPORTED_CLAIM = "UNSUPPORTED_CLAIM"
    OVERGENERALIZATION = "OVERGENERALIZATION"
    SCOPE_MISMATCH = "SCOPE_MISMATCH"
    EVIDENCE_MISMATCH = "EVIDENCE_MISMATCH"
    OWNERSHIP_CONFUSION = "OWNERSHIP_CONFUSION"
    CAUSALITY_INFLATION = "CAUSALITY_INFLATION"
    CONTRADICTION_IGNORED = "CONTRADICTION_IGNORED"
    ASSUMPTION_UNTESTED = "ASSUMPTION_UNTESTED"
    ALTERNATIVE_UNTESTED = "ALTERNATIVE_UNTESTED"
    LEAKAGE_RISK = "LEAKAGE_RISK"
    SHORTCUT_RISK = "SHORTCUT_RISK"
    BASELINE_UNFAIR = "BASELINE_UNFAIR"
    METRIC_MISMATCH = "METRIC_MISMATCH"
    BENCHMARK_LIMITATION = "BENCHMARK_LIMITATION"
    PRIVACY_OVERCLAIM = "PRIVACY_OVERCLAIM"
    OPERATIONAL_OVERCLAIM = "OPERATIONAL_OVERCLAIM"
    NOVELTY_OVERCLAIM = "NOVELTY_OVERCLAIM"
    REPRESENTATION_DETECTOR_CONFOUND = "REPRESENTATION_DETECTOR_CONFOUND"
    ATTACK_ANOMALY_CONFLATION = "ATTACK_ANOMALY_CONFLATION"
    ATTACK_TAXONOMY_MISUSE = "ATTACK_TAXONOMY_MISUSE"
    TEMPLATE_ATTRACTOR_RISK = "TEMPLATE_ATTRACTOR_RISK"
    CIRCULAR_REASONING = "CIRCULAR_REASONING"


class DiscourseFunction(str, Enum):
    """Chức năng tu từ của diễn ngôn (Gợi ý 5 Mục 53)."""
    DEFINE = "DEFINE"
    DELIMIT = "DELIMIT"
    DISTINGUISH = "DISTINGUISH"
    COMPARE = "COMPARE"
    CONTRAST = "CONTRAST"
    SYNTHESIZE = "SYNTHESIZE"
    EXPLAIN_MECHANISM = "EXPLAIN_MECHANISM"
    PRESENT_EVIDENCE = "PRESENT_EVIDENCE"
    QUALIFY = "QUALIFY"
    COUNTERARGUE = "COUNTERARGUE"
    RESOLVE_CONFLICT = "RESOLVE_CONFLICT"
    DERIVE = "DERIVE"
    MOTIVATE = "MOTIVATE"
    HYPOTHESIZE = "HYPOTHESIZE"
    INTERPRET = "INTERPRET"
    LIMIT = "LIMIT"
    TRANSITION = "TRANSITION"
    FALSIFY = "FALSIFY"


class ArgumentNodeType(str, Enum):
    """Các loại nút đồ thị đối số (Lời nhắc 5 Phần 40)."""
    CLAIM = "CLAIM"
    EVIDENCE = "EVIDENCE"
    ASSUMPTION = "ASSUMPTION"
    HYPOTHESIS = "HYPOTHESIS"
    COUNTERCLAIM = "COUNTERCLAIM"
    QUALIFICATION = "QUALIFICATION"
    INFERENCE = "INFERENCE"
    CONCLUSION = "CONCLUSION"
    EXPERIMENT = "EXPERIMENT"
    OPEN_QUESTION = "OPEN_QUESTION"
    DECISION = "DECISION"
    GAP = "GAP"


class ArgumentEdgeType(str, Enum):
    """Các loại cạnh của đồ thị đối số (Nhắc 5 Phần 40)."""
    SUPPORTS = "SUPPORTS"
    CONTRADICTS = "CONTRADICTS"
    QUALIFIES = "QUALIFIES"
    ASSUMES = "ASSUMES"
    DEPENDS_ON = "DEPENDS_ON"
    DERIVED_FROM = "DERIVED_FROM"
    MOTIVATES = "MOTIVATES"
    TESTED_BY = "TESTED_BY"
    FALSIFIES = "FALSIFIES"
    REPLICATES = "REPLICATES"
    GENERALIZES = "GENERALIZES"
    SPECIALIZES = "SPECIALIZES"
    EXPLAINS = "EXPLAINS"
    ALTERNATIVE_TO = "ALTERNATIVE_TO"


class RQStatus(str, Enum):
    """Câu hỏi nghiên cứu Tình trạng nhận thức (Nhắc 5 Mục 37)."""
    OPEN = "OPEN"
    PARTIALLY_ANSWERED = "PARTIALLY_ANSWERED"
    ANSWERED_WITH_LIMITATIONS = "ANSWERED_WITH_LIMITATIONS"
    CONTESTED = "CONTESTED"
    BLOCKED = "BLOCKED"


class NoveltyReasoningState(str, Enum):
    """Vòng đời lý luận mới lạ chi tiết (Lời nhắc 5 Phần 39)."""
    CANDIDATE = "CANDIDATE"
    PRIOR_ART_SEARCHED = "PRIOR_ART_SEARCHED"
    POTENTIALLY_NOVEL = "POTENTIALLY_NOVEL"
    PARTIALLY_NOVEL = "PARTIALLY_NOVEL"
    NOT_NOVEL = "NOT_NOVEL"
    NOVELTY_UNRESOLVED = "NOVELTY_UNRESOLVED"


class VerificationRequestType(str, Enum):
    """Các loại yêu cầu xác minh khoa học cho giao diện Lời nhắc 6 (Lời nhắc 5 Phần 103, Lời nhắc 6 Phần 5)."""
    EQUATION_CHECK = "EQUATION_CHECK"
    EQUATION_VERIFY = "EQUATION_VERIFY"
    EQUATION_DERIVE = "EQUATION_DERIVE"
    NUMERICAL_CHECK = "NUMERICAL_CHECK"
    STATISTICAL_TEST = "STATISTICAL_TEST"
    EFFECT_SIZE = "EFFECT_SIZE"
    CONFIDENCE_INTERVAL = "CONFIDENCE_INTERVAL"
    TABLE_BUILD = "TABLE_BUILD"
    FIGURE_BUILD = "FIGURE_BUILD"
    DATASET_VALIDATE = "DATASET_VALIDATE"
    METRIC_RECOMPUTE = "METRIC_RECOMPUTE"
    RESULT_REPRODUCE = "RESULT_REPRODUCE"


class VerificationRequestStatus(str, Enum):
    """Vòng đời xử lý yêu cầu xác minh (Lời nhắc 6 Phần 5)."""
    REQUESTED = "REQUESTED"
    VALIDATING = "VALIDATING"
    READY = "READY"
    RUNNING = "RUNNING"
    PASS = "PASS"
    FAIL = "FAIL"
    INCONCLUSIVE = "INCONCLUSIVE"
    BLOCKED = "BLOCKED"
    SUPERSEDED = "SUPERSEDED"
    # Bí danh kế thừa/tương thích
    PENDING = "REQUESTED"
    IN_PROGRESS = "RUNNING"
    VERIFIED = "PASS"
    REJECTED = "FAIL"
    FAILED = "FAIL"


class ResearchPriorityLevel(str, Enum):
    """Ưu tiên hành động nghiên cứu thu được thông tin (Lời nhắc 5 Phần 107)."""
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class ArgumentPatternType(str, Enum):
    """Các mẫu đối số không cứng nhắc có thể tái sử dụng (Nhắc 5 Phần 55)."""
    PROBLEM_MECHANISM_CONSEQUENCE = "PROBLEM_MECHANISM_CONSEQUENCE"
    CLAIM_EVIDENCE_QUALIFICATION = "CLAIM_EVIDENCE_QUALIFICATION"
    METHOD_A_VS_METHOD_B_TRADEOFF = "METHOD_A_VS_METHOD_B_TRADEOFF"
    ASSUMPTION_VIOLATION_FAILURE = "ASSUMPTION_VIOLATION_FAILURE"
    OBSERVATION_ALTERNATIVES_DISCRIMINATING_TEST = "OBSERVATION_ALTERNATIVES_DISCRIMINATING_TEST"
    PRIOR_WORK_LIMITATION_GAP = "PRIOR_WORK_LIMITATION_GAP"
    RESULT_ALTERNATIVE_CONTROL_INTERPRETATION = "RESULT_ALTERNATIVE_CONTROL_INTERPRETATION"
    BENEFIT_COST_BOUNDARY = "BENEFIT_COST_BOUNDARY"
    CLAIM_COUNTEREXAMPLE_REFINED_CLAIM = "CLAIM_COUNTEREXAMPLE_REFINED_CLAIM"
    EVIDENCE_LIMITATION_NARROWED_CONCLUSION = "EVIDENCE_LIMITATION_NARROWED_CONCLUSION"


class SymbolicEqualityState(str, Enum):
    """Phân loại tương đương biểu thức ký hiệu (Nhắc 6 Phần 14)."""
    PROVEN_EQUIVALENT = "PROVEN_EQUIVALENT"
    NUMERICALLY_CONSISTENT = "NUMERICALLY_CONSISTENT"
    NOT_EQUIVALENT = "NOT_EQUIVALENT"
    UNDETERMINED = "UNDETERMINED"
    DOMAIN_DEPENDENT = "DOMAIN_DEPENDENT"
    PARSE_FAILED = "PARSE_FAILED"


class EquationType(str, Enum):
    """Phân loại phương trình khoa học (Dấu nhắc 6 Mục 10, RC-09)."""
    SOURCE_EQUATION = "SOURCE_EQUATION"
    DERIVED_EQUATION = "DERIVED_EQUATION"
    OUR_EQUATION = "OUR_EQUATION"
    OBJECTIVE_FUNCTION = "OBJECTIVE_FUNCTION"
    LOSS_FUNCTION = "LOSS_FUNCTION"
    REPRESENTATION_TRANSFORM = "REPRESENTATION_TRANSFORM"
    METRIC_FORMULA = "METRIC_FORMULA"
    BOUND_OR_INEQUALITY = "BOUND_OR_INEQUALITY"
    EMPIRICAL_RELATION = "EMPIRICAL_RELATION"


class NumericalClaimType(str, Enum):
    """Phân loại nguồn gốc yêu cầu bằng số (Nhắc 6 Phần 50)."""
    SOURCE_REPORTED = "SOURCE_REPORTED"
    RECOMPUTED = "RECOMPUTED"
    EXPERIMENT_RESULT = "EXPERIMENT_RESULT"
    DERIVED = "DERIVED"
    ESTIMATE = "ESTIMATE"


class TableType(str, Enum):
    """Phân loại bảng khoa học (Dấu nhắc 6 Phần 54)."""
    EVIDENCE_TABLE = "EVIDENCE_TABLE"
    COMPUTED_TABLE = "COMPUTED_TABLE"
    SUMMARY_TABLE = "SUMMARY_TABLE"
    CONFIGURATION_TABLE = "CONFIGURATION_TABLE"
    TRACEABILITY_TABLE = "TRACEABILITY_TABLE"


class FigureType(str, Enum):
    """Các kiểu hình dung khoa học (Gợi ý 6 Phần 67)."""
    LINE_PLOT = "LINE_PLOT"
    SCATTER_PLOT = "SCATTER_PLOT"
    BAR_PLOT = "BAR_PLOT"
    BOX_PLOT = "BOX_PLOT"
    PR_CURVE = "PR_CURVE"
    ROC_CURVE = "ROC_CURVE"
    ABLATION_PLOT = "ABLATION_PLOT"
    PARETO_FRONTIER = "PARETO_FRONTIER"
    LATENCY_THROUGHPUT = "LATENCY_THROUGHPUT"
    ROBUSTNESS_CURVE = "ROBUSTNESS_CURVE"


class ReproducibilityLevel(str, Enum):
    """Hệ thống phân cấp khả năng tái tạo 5 bậc (Nhắc 6 Mục 80)."""
    LEVEL_1_INTEGRITY = "LEVEL_1_INTEGRITY"
    LEVEL_2_METRIC = "LEVEL_2_METRIC"
    LEVEL_3_ANALYSIS = "LEVEL_3_ANALYSIS"
    LEVEL_4_RERUN = "LEVEL_4_RERUN"
    LEVEL_5_END_TO_END = "LEVEL_5_END_TO_END"


class AllowedWordingStrength(str, Enum):
    """Giới hạn chính sách về từ ngữ khoa học đối với việc viết luận văn (Nhắc 6 Phần 139)."""
    DESCRIPTIVE_ONLY = "DESCRIPTIVE_ONLY"
    ASSOCIATIONAL = "ASSOCIATIONAL"
    COMPARATIVE = "COMPARATIVE"
    SUPPORTIVE = "SUPPORTIVE"
    STRONG_SUPPORT = "STRONG_SUPPORT"
    INCONCLUSIVE = "INCONCLUSIVE"


class MetricGranularity(str, Enum):
    """Chi tiết đánh giá số liệu đo từ xa (Nhắc 6 Phần 29)."""
    EVENT = "EVENT"
    ENTITY = "ENTITY"
    SESSION = "SESSION"
    HOST = "HOST"
    CAMPAIGN = "CAMPAIGN"
    SUBGRAPH = "SUBGRAPH"


class ProtocolLockState(str, Enum):
    """Vòng đời thực thi giao thức thử nghiệm (Lời nhắc 6 Phần 83)."""
    DRAFT = "DRAFT"
    LOCKED = "LOCKED"
    EXECUTED = "EXECUTED"
    DEVIATED = "DEVIATED"
    CLOSED = "CLOSED"


class UnitOfMeasurement(str, Enum):
    """Các đơn vị vật lý và máy tính được tiêu chuẩn hóa (Nhắc 6 Mục 91)."""
    MILLISECONDS = "ms"
    SECONDS = "s"
    EVENTS_PER_SEC = "events/s"
    MB = "MB"
    GB = "GB"
    COUNT = "count"
    PERCENT = "%"
    PROBABILITY = "probability"
    DIMENSIONLESS = "dimensionless"


class TransformationOp(str, Enum):
    """Các phép biến đổi toán học và đạo hàm (Lời nhắc 6 Phần 11)."""
    SUBSTITUTE = "SUBSTITUTE"
    EXPAND = "EXPAND"
    FACTOR = "FACTOR"
    DIFFERENTIATE = "DIFFERENTIATE"
    INTEGRATE = "INTEGRATE"
    REARRANGE = "REARRANGE"
    SIMPLIFY = "SIMPLIFY"
    APPLY_IDENTITY = "APPLY_IDENTITY"
    APPLY_DEFINITION = "APPLY_DEFINITION"
    APPROXIMATE = "APPROXIMATE"


# ======================================================================
# PROMPT 7 ENUMS: ACADEMIC COMPOSER, ANTI-HALLUCINATION & THESIS AUDITOR
# ======================================================================

class DiscourseFunction(str, Enum):
    """Chức năng của bước diễn ngôn tu từ và tranh luận (Lời nhắc 5 Phần 53, Lời nhắc 7 Phần 7)."""
    # Nhắc 5 chức năng chi tiết
    DEFINE = "DEFINE"
    DELIMIT = "DELIMIT"
    DISTINGUISH = "DISTINGUISH"
    COMPARE = "COMPARE"
    CONTRAST = "CONTRAST"
    SYNTHESIZE = "SYNTHESIZE"
    EXPLAIN_MECHANISM = "EXPLAIN_MECHANISM"
    PRESENT_EVIDENCE = "PRESENT_EVIDENCE"
    QUALIFY = "QUALIFY"
    COUNTERARGUE = "COUNTERARGUE"
    RESOLVE_CONFLICT = "RESOLVE_CONFLICT"
    DERIVE = "DERIVE"
    MOTIVATE = "MOTIVATE"
    HYPOTHESIZE = "HYPOTHESIZE"
    INTERPRET = "INTERPRET"
    LIMIT = "LIMIT"
    TRANSITION = "TRANSITION"
    FALSIFY = "FALSIFY"
    # Nhắc 7 chức năng tổng hợp
    CLAIM_INTRODUCTION = "CLAIM_INTRODUCTION"
    EVIDENCE_INTEGRATION = "EVIDENCE_INTEGRATION"
    HYPOTHESIS_FORMULATION = "HYPOTHESIS_FORMULATION"
    MECHANISM_EXPLANATION = "MECHANISM_EXPLANATION"
    COUNTERARGUMENT_HANDLING = "COUNTERARGUMENT_HANDLING"
    SYNTHESIS_AND_IMPLICATION = "SYNTHESIS_AND_IMPLICATION"
    LIMITATION_BOUNDING = "LIMITATION_BOUNDING"


class WritingReadiness(str, Enum):
    """Trạng thái sẵn sàng ghi nút lộ trình (Lời nhắc 7 Phần 4)."""
    NOT_READY = "NOT_READY"
    PROVISIONAL = "PROVISIONAL"
    READY = "READY"
    BLOCKED = "BLOCKED"
    DRAFTED = "DRAFTED"
    AUDITED = "AUDITED"
    APPROVED = "APPROVED"


class SentenceClaimType(str, Enum):
    """Phân loại mệnh đề cấp độ câu (Nhắc 7 Phần 8)."""
    SOURCE_FACT = "SOURCE_FACT"
    SOURCE_CLAIM = "SOURCE_CLAIM"
    SYNTHESIS = "SYNTHESIS"
    OUR_INFERENCE = "OUR_INFERENCE"
    OUR_DESIGN = "OUR_DESIGN"
    EXPERIMENT_RESULT = "EXPERIMENT_RESULT"
    HYPOTHESIS = "HYPOTHESIS"
    TRANSITION = "TRANSITION"
    INTERPRETATION = "INTERPRETATION"
    LIMITATION = "LIMITATION"


class SentenceCompilationState(str, Enum):
    """Trạng thái biên soạn câu chống ảo giác (Nhắc 7 mục 10)."""
    DRAFT = "DRAFT"
    VALIDATING = "VALIDATING"
    PASS = "PASS"
    NEEDS_CITATION = "NEEDS_CITATION"
    UNSUPPORTED = "UNSUPPORTED"
    OWNERSHIP_CONFLICT = "OWNERSHIP_CONFLICT"
    NUMERICALLY_UNVERIFIED = "NUMERICALLY_UNVERIFIED"
    EQUATION_UNVERIFIED = "EQUATION_UNVERIFIED"
    OVERGENERALIZED = "OVERGENERALIZED"
    CONTRADICTION_IGNORED = "CONTRADICTION_IGNORED"
    SCOPE_MISMATCH = "SCOPE_MISMATCH"
    REJECTED = "REJECTED"


class ParagraphReviewStatus(str, Enum):
    """Trạng thái đánh giá và vòng đời đoạn IR của tài liệu (Nhắc 7 Mục 83)."""
    DRAFT = "DRAFT"
    GENERATED = "GENERATED"
    AUDIT_FAILED = "AUDIT_FAILED"
    MACHINE_AUDITED = "MACHINE_AUDITED"
    HUMAN_REVIEW_PENDING = "HUMAN_REVIEW_PENDING"
    HUMAN_ACCEPTED = "HUMAN_ACCEPTED"
    HUMAN_REJECTED = "HUMAN_REJECTED"
    STALE = "STALE"


class AuditCategory(str, Enum):
    """Luận án Các hạng mục kiểm toán đa chiều (Lời nhắc 7 Phần 57)."""
    CLAIMS = "CLAIMS"
    CITATIONS = "CITATIONS"
    OWNERSHIP = "OWNERSHIP"
    LOGIC = "LOGIC"
    NUMBERS = "NUMBERS"
    STATISTICS = "STATISTICS"
    EQUATIONS = "EQUATIONS"
    TABLES = "TABLES"
    FIGURES = "FIGURES"
    ARGUMENTATION = "ARGUMENTATION"
    VALIDITY = "VALIDITY"
    REPRODUCIBILITY = "REPRODUCIBILITY"
    TERMINOLOGY = "TERMINOLOGY"
    STRUCTURE = "STRUCTURE"
    STYLE = "STYLE"
    REPETITION = "REPETITION"
    CONTRIBUTIONS = "CONTRIBUTIONS"
    RQ_H_COVERAGE = "RQ_H_COVERAGE"


class AuditSeverity(str, Enum):
    """Kiểm toán phát hiện mức độ nghiêm trọng (Lời nhắc 7 Mục 131)."""
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


class AuditIssueStatus(str, Enum):
    """Vòng đời của các vấn đề kiểm toán đã xác định (Lời nhắc 7 Mục 132)."""
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    FIXED = "FIXED"
    WAIVED = "WAIVED"
    FALSE_POSITIVE = "FALSE_POSITIVE"


class CompositionMode(str, Enum):
    """Các chế độ biên soạn luận án (Nhắc 7 Mục 54-55)."""
    PROVISIONAL = "PROVISIONAL"
    FINAL = "FINAL"


class DefensibilityStatus(str, Enum):
    """10 Tình trạng đánh giá câu hỏi về khả năng bào chữa (Nhắc 7 Mục 99)."""
    PASS = "PASS"
    PARTIAL = "PARTIAL"
    FAIL = "FAIL"
    NOT_APPLICABLE = "NOT_APPLICABLE"

